# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/23 05:37:35 by kiroussa          #+#    #+#              #
#    Updated: 2024/06/25 16:05:02 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	shakespeare

include ../common-prelude.mk

SRC			=	cursor/shk_cursor_backspace.c \
				cursor/shk_cursor_backward.c \
				cursor/shk_cursor_delete.c \
				cursor/shk_cursor_forward.c \
				cursor/shk_cursor_jump.c \
				cursor/shk_cursor_jump_end.c \
				cursor/shk_cursor_jump_start.c \
				draw/shk_cursor_pos.c \
				draw/shk_redraw.c \
				draw/shk_redraw_after.c \
				history/shk_history_clear.c \
				history/shk_history_pop.c \
				history/shk_history_push.c \
				shakespeare.c \
				shk_destroy.c \
				shk_handle_escape.c \
				shk_init.c \
				shk_prompt_draw.c \
				shk_prompt_len.c \
				shk_shared.c

include ../common.mk
