# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/23 05:37:35 by kiroussa          #+#    #+#              #
#    Updated: 2024/06/23 06:46:07 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	shakespeare

include ../common-prelude.mk

SRC			=	history/shk_history_clear.c \
				history/shk_history_pop.c \
				history/shk_history_push.c \
				shakespeare.c \
				shk_destroy.c \
				shk_init.c \
				shk_shared.c

include ../common.mk
