# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 06:49:07 by kiroussa          #+#    #+#              #
#    Updated: 2024/05/17 18:15:14 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 		=	builtins
DEPS		=	shared

include ../common-prelude.mk

SRC			=	core/msh_builtin_count.c \
				core/msh_builtin_get.c \
				core/msh_builtin_help_page.c \
				core/msh_builtin_print_help.c \
				core/msh_builtin_print_usage.c \
				core/msh_builtin_register.c \
				core/msh_builtin_registry.c \
				bash/_wip.c \
				bash/help.c \
				minishell/env.c \
				posix/echo.c \
				posix/exit.c \
				posix/no-op.c \
				posix/pwd.c

include ../common.mk
