# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 06:49:07 by kiroussa          #+#    #+#              #
#    Updated: 2024/05/15 23:14:09 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 		=	builtins
DEPS		=	shared

include ../common-prelude.mk

SRC			=	core/msh_builtin_get.c \
				core/msh_builtin_help_page.c \
				core/msh_builtin_print_help.c \
				core/msh_builtin_print_usage.c \
				core/msh_builtin_register.c \
				core/msh_builtin_registry.c \
				_wip.c \
				echo.c \
				env.c \
				exit.c \
				help.c \
				no-op.c \
				pwd.c

include ../common.mk
