# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/26 20:43:55 by kiroussa          #+#    #+#              #
#    Updated: 2024/04/26 20:44:47 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	ast-preprocessor
DEPS		=	shared ast-tokenizer

include ../common-prelude.mk

SRC			=	msh_ast_tkn_merge.c \
				msh_ast_tkn_verify.c

include ../common.mk
