# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/21 13:19:27 by kiroussa          #+#    #+#              #
#    Updated: 2024/05/21 15:45:01 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	ast-shared
DEPS		=	shared

include ../common-prelude.mk

SRC			=	error/msh_ast_err.c \
				error/msh_ast_errd.c \
				error/msh_ast_error_print.c \
				error/msh_ast_ok.c \
				error/msh_ast_okd.c \
				error/msh_ast_perror.c \
				error/msh_ast_strerror.c

include ../common.mk
