# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/05/23 21:13:03 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	xft-getopt

include ../common-prelude.mk

SRC			=	long/ft_opt_get_long.c \
				posix/ft_opt_get_posix.c \
				wchar/ft_bittab.c \
				wchar/ft_bittab_ranges.c \
				wchar/ft_codeunit.c \
				wchar/ft_illegal_sequence.c \
				wchar/ft_mbtowc.c \
				wchar/ft_wchar_oob.c \
				ft_opt_args.c \
				ft_opt_get.c \
				ft_opt_globals.c \
				ft_opt_msg.c \
				ft_opt_permute.c \
				ft_opt_reset.c

include ../common.mk
