# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/05/22 19:15:35 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	getopt

include ../common-prelude.mk

SRC			=	ft_opt_args.c \
				ft_opt_globals.c \
				ft_opt_reset.c

include ../common.mk
