# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/08/21 13:38:58 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	ast-lexer-sanitizer
DEPS		=	ast-lexer

include ../common-prelude.mk

SRC			=	msh_ast_sanitize.c \
				msh_ast_strtoken_simple.c \
				msh_ast_syntax_error.c

include ../common.mk
