# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/05/15 22:57:32 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	executor
DEPS		=	builtins

include ../common-prelude.mk

SRC			=	msh_exec_simple.c \
				msh_exec_status.c

include ../common.mk
