# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/07/16 17:37:42 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	ast-sanitizer
DEPS		=	ast-lexer ast-builder

include ../common-prelude.mk

SRC			=	msh_ast_sanitize.c \
				msh_ast_sanitize_check.c \
				msh_ast_sanitize_merge.c \
				msh_ast_sanitize_optimize.c

include ../common.mk
