# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/07/18 01:44:39 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	ast-sanitizer
DEPS		=	ast-lexer

include ../common-prelude.mk

SRC			=	merge/msh_ast_merge_strtostr.c \
				merge/msh_ast_merge_strtow.c \
				merge/msh_ast_merge_wtostr.c \
				merge/msh_ast_merge_wtow.c \
				msh_ast_sanitize.c \
				msh_ast_sanitize_check.c \
				msh_ast_sanitize_merge.c \
				msh_ast_sanitize_standardize.c

include ../common.mk
