# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/05/22 03:05:14 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	shared

include ../common-prelude.mk

SRC			=	env/msh_env_defaults.c \
				env/msh_env_find.c \
				env/msh_env_free.c \
				env/msh_env_free_all.c \
				env/msh_env_get.c \
				env/msh_env_populate.c \
				env/msh_env_print_assignment.c \
				env/msh_env_push.c \
				env/msh_env_sorted.c \
				env/msh_env_tab.c \
				env/msh_env_tab_free.c \
				env/msh_env_value.c \
				log/msh_error.c \
				log/msh_log.c \
				log/msh_vlog.c \
				log/msh_warn.c \
				signal/msh_signal_handler.c \
				signal/msh_signal_init.c \
				signal/msh_signal_setdfl.c \
				signal/msh_strsignal.c \
				util/msh_ansicstr.c \
				util/msh_columns.c \
				util/msh_contains_shell_metas.c \
				util/msh_fileno.c \
				util/msh_get_hostname.c \
				util/msh_geteuid.c \
				util/msh_is_directory.c \
				util/msh_is_interactive.c \
				util/msh_quote.c \
				util/msh_resolve_path.c \
				util/msh_same_file.c \
				util/msh_strcoll.c \
				msh_destroy.c \
				msh_exit.c \
				msh_init.c

include ../common.mk
