name: Build minishell

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'
    - name: Build minishell 
      run: make re
