name: Build minishell

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install norminette
      run: pip install -U norminette
    - name: Norm check 
      run: norminette submodules | grep Error
