name: Norm check 

on:
 push:
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install norminette
      run: pip install -U norminette
    - name: Print norminette version
      run: norminette --version
    - name: Norm check 
      run: norminette ./submodules
